background = 0xFF1e1e2e
base = 0xFF181825
alternate_base = 0xFF313244
text = 0xFFcdd6f4
bright_text = 0xFFffffff
accent = 0xFFb4befe
accent_secondary = 0xFFcba6f7

rounding_large = 10
rounding_small = 5
