source = $HOME/.config/hypr/themes/mocha.conf

$accent = $mauve
$accentAlpha = $mauveAlpha
$font = JetBrainsMono Nerd Font

# GENERAL
general {
  disable_loading_bar = true
  hide_cursor = true
}

# BACKGROUND
background {
  monitor =
  path = $HOME/Pictures/wallpapers/lighthouse-2.png
  
  # Slightly less blur
  blur_passes = 1
  blur_size = 5
  
  # Dimming the wallpaper (1.0 is full brightness, lower is darker)
  brightness = 0.5
  
  color = $base
}

# MODERN, CENTERED TIME
label {
  monitor =
  text = $TIME
  color = $lavender
  font_size = 120
  font_family = $font ExtraBold
  position = 0, 250
  halign = center
  valign = center
}

# MODERN, CENTERED DATE
label {
  monitor =
  text = cmd[update:43200000] date +"%A, %d %B %Y"
  color = $lavender
  font_size = 30
  font_family = $font
  position = 0, 130
  halign = center
  valign = center
}

# USER AVATAR
image {
  monitor =
  path = $HOME/.face
  size = 100
  border_color = $accent
  position = 0, -20
  halign = center
  valign = center
}

# INPUT FIELD
input-field {
  monitor =
  size = 300, 60
  outline_thickness = 4
  dots_size = 0.2
  dots_spacing = 0.2
  dots_center = true
  outer_color = $accent
  inner_color = $surface0
  
  # Typed password/text is lavender
  font_color = $lavender
  fade_on_empty = false
  
  # Placeholder text is also lavender
  placeholder_text = <span foreground="##$lavenderAlpha"><i>󰌾 Logged in as </i><span foreground="##$lavenderAlpha">$USER</span></span>
  hide_input = false
  check_color = $accent
  fail_color = $red
  fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
  capslock_color = $yellow
  position = 0, -130
  halign = center
  valign = center
}

# SUBTLE KEYBOARD LAYOUT
label {
  monitor =
  text =   $LAYOUT
  color = $lavender
  font_size = 14
  font_family = $font
  position = 0, 30
  halign = center
  valign = bottom
}
